#!/bin/bash

eval "$(/opt/homebrew/bin/brew shellenv)"

# export PATH=$PATH:/usr/bin
# export PATH=$PATH:/bin
# export PATH=$PATH:/usr/sbin
# export PATH=$PATH:/sbin
eval "$(rbenv init - bash)"

# if [[ $(uname -a | grep Darwin) ]]; then
#     export JAVA_HOME=$(/usr/libexec/java_home)
#     export PATH=$JAVA_HOME/bin:$PATH
# fi

#######################################################
#              End of path fuckery                    #
#######################################################

export EDITOR="emacs -Q"

for file in $(find ~/.bash_completion.d/*); do
  . $file
done

## Prompt
parse_git_branch() {
  git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1='\[\033[01;32m\]\u@\h:\[\033[01;34m\]\w\[\033[00m\]\[\033[01;32m\]$(parse_git_branch)\[\033[00m\] \$ '

##Aliases
source ~/.aliases

if [ -r ~/.machine_profile ]; then
  source ~/.machine_profile
fi

[[ -r $HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh ]] && . $HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh

# #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
# export SDKMAN_DIR="/Users/jhirn/.sdkman"
# [[ -s "/Users/jhirn/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/jhirn/.sdkman/bin/sdkman-init.sh"

if [ -r ~/.cargo/env ]; then
  . "$HOME/.cargo/env"
fi
