
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/jhirn/.sdkman"
[[ -s "/Users/jhirn/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/jhirn/.sdkman/bin/sdkman-init.sh"
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/jhirn/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
